sonar.organization=mihaly-farkas
sonar.projectKey=mihaly-farkas_spring-cloud-config-server
sonar.coverage.exclusions=src/main/java/io/github/mihaly_farkas/spring_cloud_config_server/SpringCloudConfigServer.java
