sonar.organization=mihaly-farkas
sonar.projectKey=mihaly-farkas_spring-boot-config-server
sonar.coverage.exclusions=src/main/java/io/github/mihaly_farkas/spring_boot_config_server/SpringBootConfigServer.java
